### ISSUE TITLE
Add daily updates to Jason

### ISSUE THREAD

**Issue by Encodation** [JasonLovesDoggo/foodle-api#3]
Add daily updates via the signal API

challenges...
- security: keep my phone num and API key safe 
- running:  prob use a cron trigger to run or have it be an API endpoint but that's prob, not the best idea so I'm almost certainly going to go with the separate file running on a cron trigger and using an env file

**Comment by Encodation** [comment]
@JasonLovesDoggo

**Comment by JasonLovesDoggo** [comment]
will be done.. see the next update for more info
